### ISSUE TITLE
Hi  there ,  Could you release the code and model?

### ISSUE THREAD

**Issue by Luccadoremi** [ErenChan/UKSDG#2]

**Comment by ErenChan** [comment]
hi，
Codes can be downloaded from the Baidu SkyDrive link:  https://pan.baidu.com/s/1tOfwk0ASswgNMRO57Yl7bA and the extraction code is ''ecuu''.
Ckpts can be downloaded from the Baidu SkyDrive link: https://pan.baidu.com/s/1InPALoRXI26_vqkoS50PhA and the extraction code is ''1wzh''.

**Comment by Luccadoremi** [comment]
> hi， Codes can be downloaded from the Baidu SkyDrive link: https://pan.baidu.com/s/1tOfwk0ASswgNMRO57Yl7bA and the extraction code is ''ecuu''. Ckpts can be downloaded from the Baidu SkyDrive link: https://pan.baidu.com/s/1InPALoRXI26_vqkoS50PhA and the extraction code is ''1wzh''.

thanks :)

**Comment by mashangzhao** [comment]
> 

hi, could you share again? thanks

**Comment by mashangzhao** [comment]
> hi， Codes can be downloaded from the Baidu SkyDrive link: https://pan.baidu.com/s/1tOfwk0ASswgNMRO57Yl7bA and the extraction code is ''ecuu''. Ckpts can be downloaded from the Baidu SkyDrive link: https://pan.baidu.com/s/1InPALoRXI26_vqkoS50PhA and the extraction code is ''1wzh''.

hi, could you share again?Thanks. Because the link is invalid.

**Comment by ErenChan** [comment]
> > hi， Codes can be downloaded from the Baidu SkyDrive link: https://pan.baidu.com/s/1tOfwk0ASswgNMRO57Yl7bA and the extraction code is ''ecuu''. Ckpts can be downloaded from the Baidu SkyDrive link: https://pan.baidu.com/s/1InPALoRXI26_vqkoS50PhA and the extraction code is ''1wzh''.
> 
> hi, could you share again?Thanks. Because the link is invalid.
hi，
New code link: https://pan.baidu.com/s/1d-XdwCs_ryF8epyazSk8QA with the extraction code "iymw"
New ckpt link: https://pan.baidu.com/s/1fKunwdCzxD0CQIRj-UvYtw with the extraction code "zvob"

Have a good day!

**Comment by mashangzhao** [comment]
> 

Thanks very much!

**Comment by aa452948257** [comment]
> New code link: https://pan.baidu.com/s/1d-XdwCs_ryF8epyazSk8QA with the extraction code "iymw"
> New ckpt link: https://pan.baidu.com/s/1fKunwdCzxD0CQIRj-UvYtw with the extraction code "zvob"
sorry, could you share again again?  Because the link is invalid. Thanks very much.

**Comment by ErenChan** [comment]
> current ckpt link：https://pan.baidu.com/s/1X9iMcMg_4Bqcrwptv6X9iA  with the extraction code "ix1m"
> current code link: https://pan.baidu.com/s/1_4jKP2LHFjeA7MNHbWusxA  with the extraction code "nx70"
Have a good day!

> > New code link: https://pan.baidu.com/s/1d-XdwCs_ryF8epyazSk8QA with the extraction code "iymw"
> > New ckpt link: https://pan.baidu.com/s/1fKunwdCzxD0CQIRj-UvYtw with the extraction code "zvob"
> > sorry, could you share again again?  Because the link is invalid. Thanks very much.

**Comment by aa452948257** [comment]
> current ckpt link：https://pan.baidu.com/s/1X9iMcMg_4Bqcrwptv6X9iA with the extraction code "ix1m"
> current code link: https://pan.baidu.com/s/1_4jKP2LHFjeA7MNHbWusxA with the extraction code "nx70"
> Have a good day!

hi, I see this code. Could you give me a readme file or tell me how to run whole project? Thanks.

**Comment by aa452948257** [comment]
I meet the following errors, but I can't deal with this problems.

Traceback (most recent call last):
  File "/Users/wangdeyuan/PycharmProjects/UKSDG/train.pretrain.py", line 270, in <module>
    main()
    └ <function main at 0x7fce32914820>
  File "/Users/wangdeyuan/PycharmProjects/UKSDG/train.pretrain.py", line 205, in main
    output_dict = trainer.train_step(example)
                  │                  └ {'context': <tf.Tensor: shape=(1, 5, 52), dtype=int32, numpy=
array([[[  101,  2054,  2001,  2115,  5440,  3496,  1999,  2023,  ...
                  └ <modules.mytrainer.Trainer object at 0x7fcde1598310>
  File "/Users/wangdeyuan/PycharmProjects/UKSDG/modules/mytrainer.py", line 52, in train_step
    return self.train_step_fn(self.model, self.optimizer, example)
           │                  │           │               └ {'context': <tf.Tensor: shape=(1, 5, 52), dtype=int32, numpy=
array([[[  101,  2054,  2001,  2115,  5440,  3496,  1999,  2023,  ...
           │                  │           └ <modules.mytrainer.Trainer object at 0x7fcde1598310>
           │                  └ <modules.mytrainer.Trainer object at 0x7fcde1598310>
           └ <modules.mytrainer.Trainer object at 0x7fcde1598310>
  File "/Users/wangdeyuan/miniconda3/lib/python3.9/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/Users/wangdeyuan/miniconda3/lib/python3.9/site-packages/tensorflow/python/eager/execute.py", line 54, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError: Graph execution error:

Input to reshape is a tensor with 125 values, but the requested shape has 255
	 [[{{node SKTpipelineTeacherPreTrain/model/bert_model/ArithmeticOptimizer/ReorderCastLikeAndValuePreserving_bool_Reshape}}]] [Op:__inference__train_step_88349]

**Comment by ErenChan** [comment]
I have graduated and can’t get the server in the laboratory anymore.
I am sorry for that, it may be caused by the env.  Moreover, I run this code with enable_function=False, while you used the eager mode.
You can set up the env following https://github.com/bckim92/sequential-knowledge-transformer

You need pretrain the knowledge selection module via pipeline_teacher_pretrain.sh, and then fintune the decoder via pipeline_teacher_decoder.sh.

**Comment by dongmingli-Ben** [comment]
The new code and checkpoint link expires too. Could you please share a new link?

**Comment by ErenChan** [comment]
> The new code and checkpoint link expires too. Could you please share a new link?

current ckpt link：https://pan.baidu.com/s/1J0n244bpSKF-kbysbrqKaA with the extraction code "xjeg"
current code link: https://pan.baidu.com/s/1Kxnxnen2-k2PX5YDTV91wQ with the extraction code "b8tx"
Sorry for the late reply. Have a good day!
